// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef bugGUI_h
#define bugGUI_h
#include <FL/Fl.H>
#include <iostream>
#include "bug.h"
#include <FL/Fl_PNG_Image.H>
Fl_PNG_Image* img[4]; 
Bug bug; 
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
extern Fl_Box *b;
#endif
